configuration:
  projectName: Spring Boot default

---
spring:
  profiles: dev
configuration:
  projectName: Spring Boot dev

---
spring:
  profiles: prod
configuration:
  projectName: Spring Boot prod